### PR TITLE
Django 1.11 compatibility

### PR DESCRIPTION
**Pull request by atiberghien**
render_option was dropped since 1.11

### CODE REVIEW

**Comment by nikordaris** [comment]
Can we get this merged?

**Comment by belek** [comment]
@redouane, can you please have a look at this fix and merge it?

**Comment by Benbb96** [comment]
I applied these modifications on Django 2.0 and it's working 😄 
It could be nice if it would be merged.

**Comment by IDLe-Engineering** [comment]
Benbb96's fixed did it for me as well. A merge would be nice

**Comment by mpena2099** [comment]
Thanks for this fix!

**Comment by ryanovas** [comment]
any update on this PR?

**Pull request merged**
